//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;

    public partial class STable
    {
        [Key]
        public int id { get; set; }
       
        
        [Required]
        public string name { get; set; }
       
        [Required]
        public string gender { get; set; }
       
        [Range(0,100)]
        public int sub1 { get; set; }

        [Range(0, 100)]
        public int sub2 { get; set; }
        
        [Range(0, 100)]
        public int sub3 { get; set; }
        
        public int total { get; set; }
    }
}
